#93: Infinite background
uclaacm/parcel-pointers pull request #186
Opened 2023-03-03 09:54 UTC by sweeneyngo

## Summary

Closes #93.

→ i forgot to PR, oops.
→ preview: `Main.tsx`

> honestly, i could make it a separate component, so let me know!⁺

2023-03-03 19:06 UTC, ajtadeo requested changes
the animation looks great! one problem i noticed is that theres a white space underneath the background if you scroll down on a larger screen size:

![image](https://user-images.githubusercontent.com/76643809/222805574-d0a43901-df40-4e2c-9c3f-060a9f02e46f.png)

2023-03-03 23:15 UTC, ajtadeo commented
Will fix the white space issue at a later time.

2023-03-03 23:42 UTC, ajtadeo approved these changes

2023-03-04 00:01 UTC, sweeneyngo commented
> the animation looks great! one problem i noticed is that theres a white space underneath the background if you scroll down on a larger screen size:
> 
> ![image](https://user-images.githubusercontent.com/76643809/222805574-d0a43901-df40-4e2c-9c3f-060a9f02e46f.png)

fixed! [c9077da.](https://github.com/uclaacm/parcel-pointers/pull/186/commits/c9077da4141fc5e657676b892f8d591638fc7963)

2023-03-04 00:01 UTC, merged